name: Checkout
description: Checkout repository

inputs:
  fetch-depth:
    description: "Depth of fetching"
    required: false
    default: "1"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      shell: bash
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
