name: Setup Poetry Environment
description: Install Python and Poetry with caching for reproducible builds

inputs:
  python-version:
    description: Python version to use
    default: "3.12"
  poetry-version:
    description: Poetry version to install
    default: "1.8.3"

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      shell: bash
      run: |
        pip install --upgrade pip
        pip install poetry==${{ inputs.poetry-version }}

    - name: Add Poetry to PATH
      shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Verify Python and Poetry
      shell: bash
      run: |
        echo "Python version:"
        python --version
        echo "Poetry version:"
        poetry --version

    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          .venv
        key: ${{ runner.os }}-poetry-${{ inputs.poetry-version }}-py${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-${{ inputs.poetry-version }}-py${{ inputs.python-version }}-
          ${{ runner.os }}-poetry-
