name: Deploy Documentation

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-poetry
      - run: poetry install --no-interaction --with docs
      - run: poetry run python scripts/generate_autodoc_pages.py
      - run: poetry run mkdocs gh-deploy --force --clean
