name: Deploy Documentation

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  deploy-docs:
    concurrency: docs-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fetch gh-pages branch
        shell: bash
        run: |
          if git ls-remote --exit-code origin gh-pages > /dev/null 2>&1; then
            git fetch origin gh-pages:gh-pages
          fi

      - name: Deploy documentation
        uses: ./.github/actions/deploy-docs
        with:
          version: dev
          author-name: "forging-blocks"
          author-email: "forging-blocks-org@proton.me"
