name: Deploy Documentation

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  deploy-docs:
    concurrency: docs-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Deploy documentation
        uses: ./.github/actions/deploy-docs
        with:
          version: dev
          author-name: "forging-blocks"
          author-email: "forging-blocks-org@proton.me"
